/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Check service health */
        readonly get: operations["AppController_getHealth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health/live": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Check HTTP process liveness */
        readonly get: operations["AppController_getLiveness"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Check HTTP process readiness */
        readonly get: operations["AppController_getReadiness"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    readonly AppController_getHealth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                /** @description Optional caller-provided trace identifier. Invalid values are replaced. */
                readonly "x-request-id"?: string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description The service is available. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly data: {
                            /** @example orz-people-platform-backend */
                            readonly service: string;
                            /** @enum {string} */
                            readonly status: "ok" | "ready";
                        };
                        readonly meta: {
                            readonly requestId: string;
                            /** Format: date-time */
                            readonly timestamp: string;
                        };
                    };
                };
            };
        };
    };
    readonly AppController_getLiveness: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                /** @description Optional caller-provided trace identifier. Invalid values are replaced. */
                readonly "x-request-id"?: string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description The HTTP process is alive. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly data: {
                            /** @example orz-people-platform-backend */
                            readonly service: string;
                            /** @enum {string} */
                            readonly status: "ok" | "ready";
                        };
                        readonly meta: {
                            readonly requestId: string;
                            /** Format: date-time */
                            readonly timestamp: string;
                        };
                    };
                };
            };
        };
    };
    readonly AppController_getReadiness: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                /** @description Optional caller-provided trace identifier. Invalid values are replaced. */
                readonly "x-request-id"?: string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description The HTTP process accepts requests. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly data: {
                            /** @example orz-people-platform-backend */
                            readonly service: string;
                            /** @enum {string} */
                            readonly status: "ok" | "ready";
                        };
                        readonly meta: {
                            readonly requestId: string;
                            /** Format: date-time */
                            readonly timestamp: string;
                        };
                    };
                };
            };
        };
    };
}
